In [ ]:
pip install afinn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting afinn
  Downloading afinn-0.1.tar.gz (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 KB 6.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: afinn
  Building wheel for afinn (setup.py) ... done
  Created wheel for afinn: filename=afinn-0.1-py3-none-any.whl size=53447 sha256=9c56b19b79fca59245abb0c50b518eb6732d603c6cb7fec3bc2f8294e3224567
  Stored in directory: /root/.cache/pip/wheels/f6/6f/c3/b305c5107a17618f2938a067d5ffcbb556909d82398762089e
Successfully built afinn
Installing collected packages: afinn
Successfully installed afinn-0.1

In [ ]:
pip install nrclex

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting nrclex
  Downloading NRCLex-4.0-py3-none-any.whl (4.4 kB)
Requirement already satisfied: textblob in /usr/local/lib/python3.8/dist-packages (from nrclex) (0.15.3)
  Downloading NRCLex-3.0.0.tar.gz (396 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 396.4/396.4 KB 25.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.8/dist-packages (from textblob->nrclex) (3.7)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob->nrclex) (2022.6.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob->nrclex) (4.64.1)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob->nrclex) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob->nrclex) (1.2.0)
Building wheels for collected packages: nrclex
  Building wheel for nrclex (setup.py) ... done
  Created wheel for nrclex: filename=NRCLex-3.0.0-py3-none-any.whl size=43329 sha256=da3b2a3af305bd6b2f16d8534d4b9925fb1b60f5eb98c71b1b1ed7c9a4b3c3d9
  Stored in directory: /root/.cache/pip/wheels/83/95/c0/42b43fb15eb48e4f5a67cba8915540cb2783591c59c037a9e5
Successfully built nrclex
Installing collected packages: nrclex
Successfully installed nrclex-3.0.0

In [ ]:
pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.8/dist-packages (3.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk) (2022.6.2)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk) (7.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk) (4.64.1)

In [ ]:
import pandas as pd
import re
from afinn import Afinn
from nrclex import NRCLex

In [ ]:
lyrics=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/lyrics.csv')
lyrics.shape

(3701, 4)

In [ ]:
lyrics.head(1)

,id,track,artist,lyrics
0,6qc34bnVOyqGDPni8H5W0U,Amazed,Lonestar,Amazed Lyrics[Verse 1]\nEvery time our eyes me...

In [ ]:
audio=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/audio_features.csv')
audio.head(1)

,id,track,artist_id,artist,album_id,album,release_date,link,danceability,energy,...,liveness,valence,tempo,type,uri,track_href,analysis_url,duration_ms,time_signature,genre
0,6qc34bnVOyqGDPni8H5W0U,Amazed,3qbnxnvUqR14MJ9g8QwZJK,Lonestar,7ykiOoPC4GLrVYSDVdDGq2,Lonely Grill,1999,https://api.spotify.com/v1/tracks/6qc34bnVOyqG...,0.561,0.543,...,0.124,0.243,139.803,audio_features,spotify:track:6qc34bnVOyqGDPni8H5W0U,https://api.spotify.com/v1/tracks/6qc34bnVOyqG...,https://api.spotify.com/v1/audio-analysis/6qc3...,240867,4,country

In [ ]:
genrecol=audio[['id','genre']]
genrecol.head(2)

                       id    genre
0  6qc34bnVOyqGDPni8H5W0U  country
1  3EUl8M6SzxZl03NPkB8mUd  country

In [ ]:
lyrics=lyrics.merge(genrecol,on='id')
lyrics.head(1)

,id,track,artist,lyrics,genre
0,6qc34bnVOyqGDPni8H5W0U,Amazed,Lonestar,Amazed Lyrics[Verse 1]\nEvery time our eyes me...,country

In [ ]:
lyrics.genre.value_counts()

rock         1096
dance_pop    1037
hip_hop       978
country       590
Name: genre, dtype: int64

In [ ]:
df=lyrics
df['lyrics'] = [re.sub(r'^.*?Lyrics', '', str(lyric)) for lyric in df['lyrics']]
df['cleaned_lyrics'] = [str(lyric).replace('\n',' ') for lyric in df['lyrics']]
df['cleaned_lyrics'] = [re.sub("\[.*?\]","",lyric) for lyric in df['cleaned_lyrics']]

df['title_length'] = [len(title) for title in df['track']]
df['lines'] = [str(lyric).count('\n') for lyric in df['lyrics']]
df['sections'] = [str(lyric).count('\n\n') for lyric in df['lyrics']]
df['verse_count'] = [str(lyric).count('[Verse') for lyric in df['lyrics']]
df['chorus_count'] = [str(lyric).count('[Chorus') for lyric in df['lyrics']]
df['dash_count'] = [str(lyric).count('" -') for lyric in df['lyrics']]
df['words'] = [len(str(lyric).split()) for lyric in df['cleaned_lyrics']]
df['unique_words'] = [len(set(str(lyric).split())) for lyric in df['cleaned_lyrics']]

df.head(3)

,id,track,artist,lyrics,genre,cleaned_lyrics,title_length,lines,sections,verse_count,chorus_count,dash_count,words,unique_words
0,6qc34bnVOyqGDPni8H5W0U,Amazed,Lonestar,[Verse 1]\nEvery time our eyes meet\nThis feel...,country,Every time our eyes meet This feeling inside ...,6,55,6,2,3,0,258,99
1,3EUl8M6SzxZl03NPkB8mUd,Neon Moon,Brooks & Dunn,[Verse 1]\nWhen the sun goes down on my side o...,country,When the sun goes down on my side of town Tha...,9,62,9,5,3,0,295,133
2,7lUE02KHkZM44BZgjCaWRO,Meet In the Middle,Diamond Rio,[Verse 1]\nIt was seven hundred fence posts fr...,country,It was seven hundred fence posts from your pl...,18,44,6,2,5,0,311,103

In [ ]:
df = df[df.dash_count<3]

In [ ]:
  import nltk
  nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
df['emot_positive'] = [NRCLex(lyric).affect_frequencies.get('positive') for lyric in df['cleaned_lyrics']]
df['emot_negative'] = [NRCLex(lyric).affect_frequencies.get('negative') for lyric in df['cleaned_lyrics']]
df['emot_anger'] = [NRCLex(lyric).affect_frequencies.get('anger') for lyric in df['cleaned_lyrics']]
df['emot_trust'] = [NRCLex(lyric).affect_frequencies.get('trust') for lyric in df['cleaned_lyrics']]
df['emot_disgust'] = [NRCLex(lyric).affect_frequencies.get('disgust') for lyric in df['cleaned_lyrics']]
df['emot_fear'] = [NRCLex(lyric).affect_frequencies.get('fear') for lyric in df['cleaned_lyrics']]
df['emot_joy'] = [NRCLex(lyric).affect_frequencies.get('joy') for lyric in df['cleaned_lyrics']]
df['emot_surprise'] = [NRCLex(lyric).affect_frequencies.get('surprise') for lyric in df['cleaned_lyrics']]
df['emot_anticp'] = [NRCLex(lyric).affect_frequencies.get('anticip') for lyric in df['cleaned_lyrics']]

<ipython-input-14-909ab5adc4f7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_positive'] = [NRCLex(lyric).affect_frequencies.get('positive') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_negative'] = [NRCLex(lyric).affect_frequencies.get('negative') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_anger'] = [NRCLex(lyric).affect_frequencies.get('anger') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_trust'] = [NRCLex(lyric).affect_frequencies.get('trust') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_disgust'] = [NRCLex(lyric).affect_frequencies.get('disgust') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_fear'] = [NRCLex(lyric).affect_frequencies.get('fear') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_joy'] = [NRCLex(lyric).affect_frequencies.get('joy') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_surprise'] = [NRCLex(lyric).affect_frequencies.get('surprise') for lyric in df['cleaned_lyrics']]
<ipython-input-14-909ab5adc4f7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emot_anticp'] = [NRCLex(lyric).affect_frequencies.get('anticip') for lyric in df['cleaned_lyrics']]

In [ ]:
df.head(2)

,id,track,artist,lyrics,genre,cleaned_lyrics,title_length,lines,sections,verse_count,...,unique_words,emot_positive,emot_negative,emot_anger,emot_trust,emot_disgust,emot_fear,emot_joy,emot_surprise,emot_anticp
0,6qc34bnVOyqGDPni8H5W0U,Amazed,Lonestar,[Verse 1]\nEvery time our eyes meet\nThis feel...,country,Every time our eyes meet This feeling inside ...,6,55,6,2,...,99,0.263158,0.105263,0.052632,0.026316,0.052632,0.052632,0.157895,0.052632,0.0
1,3EUl8M6SzxZl03NPkB8mUd,Neon Moon,Brooks & Dunn,[Verse 1]\nWhen the sun goes down on my side o...,country,When the sun goes down on my side of town Tha...,9,62,9,5,...,133,0.070707,0.151515,0.131313,0.060606,0.060606,0.171717,0.070707,0.060606,0.0

In [ ]:
df['track_lower'] = df['track'].str.lower()
#remove words within brackets and paranethes in song titles 
df['track_lower'] = [re.sub("\[.*?\]","",title) for title in df['track_lower']]
df['track_lower'] = [re.sub("\(.*?\)","",title) for title in df['track_lower']]

df['track_lower'] = [str(title).replace('- single version','') for title in df['track_lower']]
df['track_lower'] = [str(title).replace('- single edit','') for title in df['track_lower']]
df['track_lower'] = [str(title).replace('- remix','') for title in df['track_lower']]
df['track_lower'] = [str(title).replace('- remix','') for title in df['track_lower']]

df['lyrics_lower'] = df['cleaned_lyrics'].astype(str)
df['lyrics_lower'] = df['lyrics_lower'].str.lower()

df['lyrics_contain_title'] = [df.loc[index]['track_lower'] in df.loc[index]['lyrics_lower'] for index in df.index]

<ipython-input-17-5efe64c8fa4b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['track_lower'] = df['track'].str.lower()
<ipython-input-17-5efe64c8fa4b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['track_lower'] = [re.sub("\[.*?\]","",title) for title in df['track_lower']]
<ipython-input-17-5efe64c8fa4b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['track_lower'] = [re.sub("\(.*?\)","",title) for title in df['track_lower']]
<ipython-input-17-5efe64c8fa4b>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['track_lower'] = [str(title).replace('- single version','') for title in df['track_lower']]
<ipython-input-17-5efe64c8fa4b>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['track_lower'] = [str(title).replace('- single edit','') for title in df['track_lower']]
<ipython-input-17-5efe64c8fa4b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['track_lower'] = [str(title).replace('- remix','') for title in df['track_lower']]
<ipython-input-17-5efe64c8fa4b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['track_lower'] = [str(title).replace('- remix','') for title in df['track_lower']]
<ipython-input-17-5efe64c8fa4b>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lyrics_lower'] = df['cleaned_lyrics'].astype(str)
<ipython-input-17-5efe64c8fa4b>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lyrics_lower'] = df['lyrics_lower'].str.lower()
<ipython-input-17-5efe64c8fa4b>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lyrics_contain_title'] = [df.loc[index]['track_lower'] in df.loc[index]['lyrics_lower'] for index in df.index]

In [ ]:
df.head(2)

,id,track,artist,lyrics,genre,cleaned_lyrics,title_length,lines,sections,verse_count,...,emot_anger,emot_trust,emot_disgust,emot_fear,emot_joy,emot_surprise,emot_anticp,track_lower,lyrics_lower,lyrics_contain_title
0,6qc34bnVOyqGDPni8H5W0U,Amazed,Lonestar,[Verse 1]\nEvery time our eyes meet\nThis feel...,country,Every time our eyes meet This feeling inside ...,6,55,6,2,...,0.052632,0.026316,0.052632,0.052632,0.157895,0.052632,0.0,amazed,every time our eyes meet this feeling inside ...,True
1,3EUl8M6SzxZl03NPkB8mUd,Neon Moon,Brooks & Dunn,[Verse 1]\nWhen the sun goes down on my side o...,country,When the sun goes down on my side of town Tha...,9,62,9,5,...,0.131313,0.060606,0.060606,0.171717,0.070707,0.060606,0.0,neon moon,when the sun goes down on my side of town tha...,True

In [ ]:
df.lyrics_contain_title.value_counts(normalize=True)

True     0.749932
False    0.250068
Name: lyrics_contain_title, dtype: float64

removing symbols and non words

In [ ]:
excl = df[(df['cleaned_lyrics'].str.contains('12.')) & (df['verse_count']==0)]
excl_ids = [i for i in excl['id']]

In [ ]:
df_lyrics = df[df['id'].isin(excl_ids)==False]
df_lyrics.shape

(3463, 26)

In [ ]:
df_lyrics.to_csv('/content/drive/MyDrive/Colab Notebooks/data_lyrics.csv', index=False)